# Generated by Django 5.1 on 2025-12-28 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('full_description', models.TextField()),
                ('dose', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSymptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.symptom')),
            ],
            options={
                'unique_together': {('medicine', 'symptom')},
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='symptoms',
            field=models.ManyToManyField(related_name='medicines', through='api.MedicineSymptom', to='api.symptom'),
        ),
    ]
