# Generated by Django 5.1 on 2026-01-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicine_medicinesymptom_medicine_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='symptoms',
        ),
    ]
